Name: farm-frenzy-3
Version: 1.0
Release: 3
# Tarball generated from installing the game available at the download
# URL by running
# WINEPREFIX=/usr/lib/games/Fram-Frenzy-3 wine farmfrenzy3_setup_full.exe
# cd /usr/lib/games/Farm-Frenzy-3
# remove-unnecessary-wine-bits
# cd ..
# tar cJf farm-frenzy-3.tar.xz Farm-Frenzy-3
Source0: farm-frenzy-3.tar.xz
# Tarball generated by running
# (after installing the game with wine as described above)
Source1: farm-frenzy-3-icons.tar.xz
Source2: winegame.c
# Used for creating source tarball, see above
Source3: remove-unnecessary-wine-bits
Summary: Farming game
URL: http://www.myplaycity.com/farm_frenzy_3/
License: Distributable
Group: Games/Arcade
ExclusiveArch: %{ix86} x86_64
%ifarch %{ix86}
Requires: wine
%else
Requires: wine32
# We need the 32bit version of ALSA's pulseaudio plugin
Requires: libalsa-plugins-pulseaudio
%endif

%description
Scarlett has been so successful in the field of farming that her fame quickly
spreads around the world. So it's not by chance when one of her friends has
problems because of the disastrous hurricane he calls the young girl and asks
for support.

Scarlett is eager to help and you can try your hand at collecting, breeding
and manufacturing goods in 5 different countries in the stunning Farm Frenzy 3
game.

Follow the helpful instructions during the first levels to learn the basics of
the game and finish each level with the golden cup. If your time will be even
better you acquire additional bonus points and can upgrade your well, truck
and cage.

Why do you need cages? Well, greedy lions appear from the blue to frighten
your poultry and animals – don't hesitate and click on them several times.

Now they are imprisoned in the firm cage and can do no harm to your farm.

Moreover, you can sell these nasty creatures to the local market (or may be a
zoo?) and get profit from your wise management. Farm Frenzy 3 will teach how
to collect feathers from ostriches and breed penguins. Apart from these
creatures you'll get acquainted with 28 other animals and learn how to make
33 products.

You've never expected you can do this without even much effort. Play
thrilling Farm Frenzy 3 game right now absolutely for free and become the
best president of the farmers' union. Achieve the highest rate and harvest
the seeds of your success!

%install
mkdir -p %{buildroot}%{_prefix}/lib/games
cd %{buildroot}%{_prefix}/lib/games
tar xf %{SOURCE0}

mkdir -p %{buildroot}%{_datadir}/icons/hicolor
cd %{buildroot}%{_datadir}/icons/hicolor
tar xf %{SOURCE1}

mkdir -p %{buildroot}%{_bindir}
%__cc %{optflags} -DGAMEPATH=\"%{_prefix}/lib/games/Farm-Frenzy-3/dosdevices/c:/Program\ Files/MyPlayCity.com/Farm\ Frenzy\ 3\" -o %{buildroot}%{_bindir}/%{name} %{SOURCE2}

mkdir -p %{buildroot}%{_datadir}/applications
cat >%{buildroot}%{_datadir}/applications/%{name}.desktop <<'EOF'
[Desktop Entry]
Name=Farm Frenzy 3
Description=Farming Game
Exec=%{_bindir}/%{name}
Type=Application
StartupNotify=true
Icon=35AF_game_icon.0
EOF

%files
%attr(6755,root,root) %{_bindir}/%{name}
%dir %{_prefix}/lib/games/Farm-Frenzy-3
%attr(0664,root,games) %{_prefix}/lib/games/Farm-Frenzy-3/*.reg
%{_prefix}/lib/games/Farm-Frenzy-3/drive_c
%{_prefix}/lib/games/Farm-Frenzy-3/dosdevices
%{_prefix}/lib/games/Farm-Frenzy-3/.update-timestamp
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/*/*/*
